### ISSUE TITLE
request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Diogo-Rodrigues** [exercism/cli#711] opened 2018-08-21 23:10 UTC
Hey guys! I just downloaded the latest release of exercism CLI (v3.0.6) for linux64, but when I tried to configure the CLI with this command 

> exercism configure --token=<MY_TOKEN>

 it doesn't work. 

> Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.
> 
> Get https://api.exercism.io/v1/ping: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

So, I found a solution for this problem using the tag 

> --no-verify

 and it seemed to work, but it didn't.

> You have configured the Exercism command-line client:
> 
> Config dir:                       /home/diogo-notebook/.config/exercism
> Token:         (-t, --token)      7642042a-02aa-4482-ad1e-09169377acbb
> Workspace:     (-w, --workspace)  /home/diogo-notebook/exercism
> API Base URL:  (-a, --api)        https://api.exercism.io/v1

When I tried to download this exercise 

> exercism download --exercise=hello-world --track=javascript

This message error appeared:

> Error: Get https://api.exercism.io/v1/solutions/latest?exercise_id=hello-world&track_id=javascript: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I'm working with Ubuntu 18.04:
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic

**Comment by kytrinyx** [comment] 2018-08-22 01:52
@Diogo-Rodrigues We've run into this before (https://github.com/exercism/cli/issues/701) and we've not yet figured out exactly what is causing it.

I'm going to see about adding a flag that will let people override (extend) the timeout, so that we can work around the problem until we figure it out.

Sorry about the trouble!

**Comment by Diogo-Rodrigues** [comment] 2018-08-22 02:49
Ok @kytrinyx, thanks for the quick answer!

**Comment by kytrinyx** [comment] 2018-08-23 02:34
I'm going to close this as a duplicate of #701 since that is where we're tracking the debugging. @Diogo-Rodrigues would you go ahead and subscribe to that issue?

**Closed by kytrinyx** 2018-08-23 02:34 UTC
Labels: type/user-support

**Comment by Diogo-Rodrigues** [comment] 2018-08-23 13:34
Yes, of course @kytrinyx ! I'm going to do that. Thanks!
