### ISSUE TITLE
Getting "sorry, tracking disabled" when fetching status of track in progress

### ISSUE THREAD

**Issue by duckpuppy** [exercism/cli#316] opened 2016-05-04 20:20 UTC
I get the following when trying to fetch the status for my in-progress language tracks.

````
$ exercism status go

Your status on the go track:

Most recently submitted exercise:
 - leap (submitted on January 25, 2016)

Exercises fetched but not submitted:
 - sorry, tracking disabled

Exercises skipped:
````

Notice that the "fetched but not submitted" has "sorry, tracking disabled".

````
$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.2.5
Exercism CLI Latest Release: 2.2.5
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/patrickaikens
Config file: /Users/patrickaikens/.exercism.json
API Key: <redacted>
Exercises Directory: /Users/patrickaikens/exercism
Testing API endpoints reachability
        * XAPI: http://x.exercism.io [connected] 77.392889ms
        * GitHub API: https://api.github.com/ [connected] 81.060083ms
        * API: http://exercism.io [connected] 474.37233ms
````

**Comment by kytrinyx** [comment] 2016-05-05 07:42
I'm closing this as a duplicate of #308

**Comment by duckpuppy** [comment] 2016-05-06 21:22
How does this duplicate that ticket?  I thought that ticket involved new tracks with no submissions.  I have two submissions already to the go track in this case.

**Comment by kytrinyx** [comment] 2016-05-08 14:25
Ahh, no you're right. Sorry about that!

**Comment by kytrinyx** [comment] 2016-05-08 18:11
OK, the problem here is that the messaging is ambiguous. We've disabled tracking for fetches. I'll clarify it.

**Closed** 2016-05-08 18:12 UTC
Labels: duplicate

**Comment by teded32** [comment] 2018-01-15 03:14
Is there a reason why tracking is disabled for fetches?

**Comment by kytrinyx** [comment] 2018-01-15 04:07
@teded32 Yeah, the tracking was experimental and turned out to add a fair amount of overhead the way we had implemented things. We're changing a number of things, and in [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) tracking will be enabled again, so we'll be able to do better reporting.
