### ISSUE TITLE
`$PWD` seems to impact later restore

### ISSUE THREAD

**Issue by magthe** [exercism/cli#152] opened 2015-01-17 15:30 UTC
Sorry for the rather cryptic title; I was struggling with making it clearer, but just gave up.  Hopefully the following explanation clarifies what I mean.  I also don't know whether this is an issue with the client or with the server, so feel free to move it if it's in the wrong location.

*Steps to reproduce*

1. Fetch a new exercise: `exercism f haskell`
2. Change directory and solve it:

        % cd haskell/newest-exercise
        % vim Module.hs
        % runhaskell newest-exercise-test.hs
        <rinse & repeat>

3. Submit exercise: `exercism s Module.hs`
4. Change back to the exercism folder: `cd ../..`
5. Remove all your haskell solutions: `rm -fr haskell`
6. Restore your haskell solutions: `exercism r haskell`

*Expected result*

I expected to find my solution in the place where I initially put it, i.e. `haskell/newest-exercise/Module.hs`.

*Observed result*

I find my solution in `haskell/newest-exercise/haskell/newest-exercise/Module.hs`.

**Comment by Tonkpils** [comment] 2015-01-17 16:18
Thanks for the detailed issue. Looking into this :+1:

**Comment by kytrinyx** [comment] 2015-01-17 17:17
This is a fantastic write-up, thank you!

My immediate thought is that the problem has to be in the client, not the API. @Tonkpils let me know if there's anything I can help dig into, or if you want to bounce ideas back and forth.

**Comment by magthe** [comment] 2015-01-17 23:09
Well, I receive my own fair share of issues, both on hobby project and at work so I like to write the kind of reports I'd like to recieive ;)

I should point out that I usually swap steps 3 and 4, i.e. I submit from the "exercism folder," and then things work as expected.

Also, forgot to give you the version of my client:

    % exercism -v
    exercism version 1.9.0

**Comment by Tonkpils** [comment] 2015-01-19 17:46
@magthe I followed the steps you've provided on this issue and I'm not able to reproduce this using the latest version of the CLI. `1.9.2` 

```sh
tonkpils@~/exercism/go/gigasecond  % exercism submit gigasecond.go

Submitted Gigasecond in Go.
Your submission can be found online at http://exercism.io/submissions/f018f582e7064bb5bd943068a673d624

To get the next exercise, run "exercism fetch" again.
tonkpils@~/exercism/go/gigasecond  % cd ../..
tonkpils@~/exercism  % rm -rf go
tonkpils@~/exercism  % exercism r go                                                          
                       New: 3 problems
                 Clock (go) /Users/tonkpils/exercism/go/clock
            Gigasecond (go) /Users/tonkpils/exercism/go/gigasecond
                  Leap (go) /Users/tonkpils/exercism/go/leap

unchanged: 20, updated: 0, new: 3
```

Are you able to update the CLI?

**Comment by magthe** [comment] 2015-01-20 07:13
It seems to be there in v 1.9.2 as well.  It's important that the exercise is previously unsolved, otherwise it doesn't show.  Hopefully the following clarifies it further:

```
% exercism --version
exercism version 1.9.2
% exercism f clojure

                       New: 1 problem
        Beer Song (clojure) /home/magnus/tmp/exercism/clojure/beer-song

unchanged: 4, updated: 0, new: 1

% cd clojure/beer-song
<solve like crazy>
% exercism s beer_song.clj

Submitted Beer Song in Clojure.
Your submission can be found online at http://exercism.io/submissions/001fa684fe6d403aa9b69b3445f0e8f5

To get the next exercise, run "exercism fetch" again.
% cd ../..
% rm -fr clojure
% exercism r clojure

                           New: 5 problems
              Anagram (clojure) /home/magnus/tmp/exercism/clojure/anagram
            Beer Song (clojure) /home/magnus/tmp/exercism/clojure/beer-song
                  Bob (clojure) /home/magnus/tmp/exercism/clojure/bob
    Rna Transcription (clojure) /home/magnus/tmp/exercism/clojure/rna-transcription
           Word Count (clojure) /home/magnus/tmp/exercism/clojure/word-count

unchanged: 41, updated: 0, new: 5

% tree clojure/beer-song 
clojure/beer-song
├── beer_song_test.clj
├── clojure
│   └── beer-song
│       └── beer_song.clj
└── README.md

2 directories, 3 files
```

**Comment by Tonkpils** [comment] 2015-01-20 18:57
Ok, interesting. I was able to reproduce the issue checking to see what it could be. I find it interesting that the solution cannot be unsolved previously.

**Comment by Tonkpils** [comment] 2015-01-20 19:48
@kytrinyx so far, what I've found out is that the list of files returned by the `http://exercism.io/api/v1/iterations/:key/restore` call contain part of the path as opposed to just the file name. 

Here's an example of what some old submissions look like when being restored:

```json
    {
      "id": "elixir\/word-count",
      "track_id": "elixir",
      "language": "elixir",
      "slug": "word-count",
      "name": "Word Count",
      "files": {
        "word_count.exs": "defmodule Words do\n  @doc \"\"\"\n  Count the number of words in the sentence.\n\n  Words are compared case-insensitively.\n  \"\"\"\n  @spec count(String.t) :: map()\n  def count(sentence) do\n\n  end\nend\n",
        "word_count_test.exs": "if System.get_env(\"EXERCISM_TEST_EXAMPLES\") do\n  Code.load_file(\"example.exs\")\nelse\n  Code.load_file(\"word_count.exs\")\nend\n\nExUnit.start\n\ndefmodule WordsTest do\n  use ExUnit.Case\n\n  test \"count one word\" do\n    assert Words.count(\"word\") == %{ \"word\" => 1 }\n  end\n\n  test \"count one of each\" do\n    expected = %{ \"one\" => 1 ,  \"of\" => 1 ,  \"each\" => 1 }\n    assert Words.count(\"one of each\") == expected\n  end\n\n  test \"count multiple occurrences\" do\n    expected = %{ \"one\" => 1 ,  \"fish\" => 4 ,  \"two\" => 1 ,  \"red\" => 1 ,  \"blue\" => 1 }\n    assert Words.count(\"one fish two fish red fish blue fish\") == expected\n  end\n\n  test \"ignore punctuation\" do\n    expected = %{\"car\" => 1, \"carpet\" => 1, \"as\" => 1, \"java\" => 1, \"javascript\" => 1}\n    assert Words.count(\"car : carpet as java : javascript!!&@$%^&\") == expected\n  end\n\n  test \"include numbers\" do\n    expected = %{\"testing\" => 2, \"1\" => 1, \"2\" => 1}\n    assert Words.count(\"testing, 1, 2 testing\") == expected\n  end\n\n  test \"hyphens\" do\n    expected = %{\"co-operative\" => 1}\n    assert Words.count(\"co-operative\") == expected\n  end\n\n  test \"ignore underscores\" do\n    expected = %{\"two\" => 1, \"words\" => 1}\n    assert Words.count(\"two_words\") == expected\n  end\n\n  test \"German\" do\n    expected = %{\"g\u00f6tterfunken\" => 1, \"sch\u00f6ner\" => 1, \"freude\" => 1}\n    assert Words.count(\"Freude sch\u00f6ner G\u00f6tterfunken\") == expected\n  end\n\n  test \"normalize case\" do\n    expected = %{\"go\" => 3}\n    assert Words.count(\"go Go GO\") == expected\n  end\nend\n",
        "README.md": "# Word Count\n\nWrite a program that given a phrase can count the occurrences of each word in that phrase.\n\nFor example for the input `\"olly olly in come free\"`\n\n```plain\nolly: 2\nin: 1\ncome: 1\nfree: 1\n```\n\n\n\n## Source\n\nThe golang tour [view source](http:\/\/tour.golang.org)\n",
        "word-count.exs": "defmodule Words do\n  def count(string) do\n    string |> downcase |> split_words |> aggregate\n  end\n\n  defp downcase(string), do: String.downcase(string)\n  defp split_words(string), do: Regex.scan(%r\/\\w+\/, string)\n  defp aggregate(word_list) do\n    Enum.reduce word_list, HashDict.new, fn(word, accumulator) -> \n      accumulator |> update_dictionary word \n    end  \n  end\n  defp update_dictionary(dictionary, word), do: HashDict.update(dictionary, word, 1, &1 + 1)\nend"
      },
      "fresh": false
    }
```

On the other hand with some of my latest submissions this is what comes back: 

```json
    {
      "id": "erlang\/leap",
      "track_id": "erlang",
      "language": "erlang",
      "slug": "leap",
      "name": "Leap",
      "files": {
        "leap_tests.erl": "% To run tests:\n% erl -make\n% erl -noshell -eval \"eunit:test(leap, [verbose])\" -s init stop\n%\n\n-module(leap_tests).\n\n-include_lib(\"eunit\/include\/eunit.hrl\").\n\nleap_year_test() ->\n    ?assert(leap:leap_year(1996)).\n\nnon_leap_year_test() ->\n    ?assertNot(leap:leap_year(1997)).\n\ncentury_test() ->\n    ?assertNot(leap:leap_year(1900)).\n\nfourth_century_test() ->\n    ?assert(leap:leap_year(2400)).\n",
        "README.md": "# Leap\n\nWrite a program that will take a year and report if it is a leap year.\n\nThe tricky thing here is that a leap year occurs:\n\n```plain\non every year that is evenly divisible by 4\n  except every year that is evenly divisible by 100\n    unless the year is also evenly divisible by 400\n```\n\nFor example, 1997 is not a leap year, but 1996 is.  1900 is not a leap\nyear, but 2000 is.\n\nIf your language provides a method in the standard library that does\nthis look-up, pretend it doesn't exist and implement it yourself.\n\n## Notes\n\nFor a delightful, four minute explanation of the whole leap year\nphenomenon, go watch [this youtube video][video].\n\n[video]: http:\/\/www.youtube.com\/watch?v=xX96xng7sAE\n\n\n## Source\n\nJavaRanch Cattle Drive, exercise 3 [view source](http:\/\/www.javaranch.com\/leap.jsp)\n",
        "\/erlang\/leap\/leap.erl": "-module(leap).\n\n-export([leap_year\/1]).\n\nleap_year(Year) ->\n\tdivisible_by(Year, 400)\n\torelse (divisible_by(Year, 4) andalso\n\t\tnot divisible_by(Year, 100)).\n\ndivisible_by(Year, Num) ->\n\tYear rem Num =:= 0."
      },
      "fresh": false
    }
```

Notice the file name for the submission contains the directory itself `"\/erlang\/leap\/leap.erl"`.

At this point I'd say this is an issue with how the API is storing the submission and returning to the client. I'm not 100% familiar with how x-api handles the submissions. Any thoughts on this?

**Comment by kytrinyx** [comment] 2015-01-21 06:08
x-api doesn't actually handle submissions (it only handles the actual language track problems + metadata). The exercism.io repo actually contains two apps, both of them are quite awful. One of them is an API that talks to the database and knows about submissions.

We've changed the data format quite a bit over time. We used to not store the filename and path at all. Later we started storing the relative path from the root exercism directory, which certainly makes it easier to handle at the CLI level.

I would be happy to write a data migration to clean up old data, if that would help fix this.

**Comment by Tonkpils** [comment] 2015-01-23 21:00
@kytrinyx just so I'm clear, the each key in the `files` hash will contain relative paths? Including the test files and the README? If that's the case, it should be an easy fix on the CLI.

**Comment by kytrinyx** [comment] 2015-01-24 17:44
Ah, no you're right, the readme and test case are given relative paths to the problem dir, no the exercism dir.

What would be a better fix?

1. Change the problems API to always return paths relative to the exercism root directory (`$TRACK/$PROBLEM/README.md`, etc), or
2. Change the exercism API to store file paths relative to the problem directory instead of the exercism root directory

Either way we'll need to do some data cleanup, and possibly update the CLI to handle things correctly.

**Comment by Tonkpils** [comment] 2015-01-24 18:27
I actually think number 2 would be good if it means what I think it means. So we would store the file path relative to the problem directory correct? I think right now the CLI takes care of storing the files in the correct problem's directory anyway.

**Comment by kytrinyx** [comment] 2015-01-24 18:41
Yeah, that's what it means. OK, cool. I'll add an issue for that, as well as the data cleanup in the history. Shouldn't be too hard!

**Comment by KaoruDev** [comment] 2015-03-05 21:11
trying to dig into this issue on the api side i was wondering if there is a easy way to point the `cli` to a localhost url. `localhost:4567`?

**Comment by Tonkpils** [comment] 2015-03-05 22:53
> trying to dig into this issue on the api side i was wondering if there is a easy way to point the cli to a localhost url. localhost:4567?

The APIs can be configured via the `configure` command or you can modify them directly through your `.exercism.json` configuration file.

**Comment by kytrinyx** [comment] 2015-03-06 14:55
@KaoruDev it's documented waaaaay at the bottom of the x-api contributing document: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#cli

**Comment by KaoruDev** [comment] 2015-03-08 20:13
got it thanks!

**Comment by kytrinyx** [comment] 2015-05-13 13:57
I think this is was fixed in the previous release. Would someone mind confirming?

**Comment by Tonkpils** [comment] 2015-05-13 15:27
I'm not sure the release fixes this issue. This issue is tied to the path received from the API during fetch. I believe we put a patch over this issue for the `download` command but not for fetching.

**Comment by kytrinyx** [comment] 2015-05-13 15:43
OK, thanks for re-reading through that and clarifying.

**Comment by kytrinyx** [comment] 2015-11-27 20:21
After re-reading this, I realize that the fix is going to need to be over in exercism, not here.

Moved to https://github.com/exercism/exercism.io/issues/2635.

**Closed by kytrinyx** 2015-11-27 20:21 UTC
Labels: bug
