### ISSUE TITLE
error parsing API response

### ISSUE THREAD

**Issue by Leandros** [exercism/cli#198] opened 2015-06-26 16:16 UTC
trying to do the demo, with `exercism demo` on osx 10.10, using the pre-compiled x64 version of the binary.

I'm getting this error:
```
2015/06/26 18:15:19 error parsing API response - invalid character '<' looking for beginning of value
```

Debug Info:
```
**** Debug Information ****
Exercism CLI Version: 2.1.1
OS/Architecture: darwin/amd64
Home Dir: /Users/arvidgerstmann
Config file: <not configured>
API Key: <not configured>
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/arvidgerstmann/exercism
```

**Comment by Tonkpils** [comment] 2015-06-26 16:27
Thank you for the report!

I've confirmed the issue and will be working on a hotfix.

**Comment by Tonkpils** [comment] 2015-06-26 16:40
I'll be closing this in favor of https://github.com/exercism/x-api/issues/61 since it seems to be an issue with the server response rather than the CLI itself.

**Closed by Tonkpils** 2015-06-26 16:40 UTC
Labels: bug
