### ISSUE TITLE
Idea: Download a whole track instead of one exercise at a time

### ISSUE THREAD

**Issue by BrunoWilkinson** [exercism/cli#990] opened 2021-04-14 11:41 UTC
### **Idea**

A download comes with a test suite and readme, so technically you can code offline and still manage to practice, my idea was what if you were about to leave for a long trip (even so it unlikely at the moment) you could download a whole track for a language and have all exercises with one command.

### Side Note

Let me know if this technically possible. If so can I lend a hand with this request.
This is not urgent, mostly a nice to have 😄

**Comment by BrunoWilkinson** [comment] 2021-05-13 14:21
@anthonygedeon maybe start a draft PR ? 

Here should be a go place to start (code wise): https://github.com/exercism/cli/blob/main/cmd/download.go

Ideally the cmd will look like this (my opinion):
```
exercism download --exercise=all --track=go
```
And it should download all the exercises for that track.

I'm not a maintainer, nor did I contribute to this repo (just a random dev passing through 😄), it will be great if we have an opinion of a maintainer, to understand better the limitation and scope as well.

**Comment by sullyj3** [comment] 2021-11-24 12:13
Dupe of #718 ?

**Comment by SleeplessByte** [comment] 2021-12-08 16:55
@sullyj3 is right!

**Closed by SleeplessByte** 2021-12-08 16:55 UTC
