### ISSUE TITLE
[Mentorcism] Invalid Memory Address

### ISSUE THREAD

**Issue by mattsp1290** [exercism/cli#572] opened 2018-06-22 16:36 UTC
I get the following when I try to download the ruby hello world exercise on macOS High Sierra

```
./mentorcism download hello-world --track=ruby
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13a1174]

goroutine 1 [running]:
github.com/exercism/cli/workspace.Workspace.Locate.func1(0xc420429500, 0x29, 0x0, 0x0, 0x150e720, 0xc4204caf90, 0x0, 0x0)
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:65 +0x44
path/filepath.Walk(0xc420429500, 0x29, 0xc4202754e0, 0x0, 0x150e720)
    /usr/local/Cellar/go/1.10.3/libexec/src/path/filepath/path.go:401 +0x6c
github.com/exercism/cli/workspace.Workspace.Locate(0xc420429500, 0x29, 0xc42028c2a0, 0xb, 0xc42014fa28, 0x1096c7a, 0xc420429500, 0x24, 0x1ed)
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:100 +0x18c
github.com/exercism/cli/workspace.Workspace.SolutionPath(0xc420429500, 0x29, 0xc42028c2a0, 0xb, 0xc4203162a0, 0x20, 0x0, 0x1, 0x0, 0x0)
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:113 +0x59
github.com/exercism/cli/cmd.glob..func2(0x17d7c80, 0xc42012c980, 0x1, 0x2, 0x0, 0x0)
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/download.go:125 +0x79d
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x17d7c80, 0xc42012c960, 0x2, 0x2, 0x17d7c80, 0xc42012c960)
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:649 +0x449
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17d7a40, 0x100620c, 0xc42009e058, 0x0)
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:728 +0x2d4
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x17d7a40, 0x0, 0xc4200b47a0)
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:687 +0x2b
github.com/exercism/cli/cmd.Execute()
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/root.go:45 +0x2d
main.main()
    /Users/kytrinyx/code/go/src/github.com/exercism/cli/exercism/main.go:6 +0x20
```

**Comment by mattsp1290** [comment] 2018-06-22 16:36
Related to [571](https://github.com/exercism/cli/issues/571)

**Comment by mattsp1290** [comment] 2018-06-22 16:42
This was fixed by configuring my workspace.

**Comment by iHiD** [comment] 2018-06-22 16:54
@mattsp1290 Thanks for opening (and closing) this. 

I've reopened this just so @kytrinyx has visibility as we might want to consider a different default workspace.

**Comment by kytrinyx** [comment] 2018-06-22 17:20
I'm going to close this as a duplicate of https://github.com/exercism/cli/issues/571 as they both have the same root cause. Thanks 🌸

**Closed by kytrinyx** 2018-06-22 17:20 UTC
Labels: mentorcism
