### ISSUE TITLE
status fails after fresh fetch

### ISSUE THREAD

**Issue by cjbottaro** [exercism/cli#308] opened 2016-04-19 01:46 UTC
Hello,

```
$ exercism fetch elixir

Not Submitted:       1 problem
elixir (Hello World) /Users/cjbottaro/Projects/exercism/elixir/hello-world

New:                 1 problem
elixir (Hello World) /Users/cjbottaro/Projects/exercism/elixir/hello-world

unchanged: 0, updated: 0, new: 1

$ exercism status elixir
2016/04/18 20:37:07 parsing time "" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "2006"

$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.2.5
Exercism CLI Latest Release: 2.2.5
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/cjbottaro
Config file: /Users/cjbottaro/.exercism.json
API Key: <snip>
Exercises Directory: /Users/cjbottaro/Projects/exercism/
Testing API endpoints reachability
	* API: http://exercism.io [connected] 167.081355ms
	* GitHub API: https://api.github.com/ [connected] 200.972461ms
	* XAPI: http://x.exercism.io [connected] 204.153389ms
```

Let me know if there is any more info I can provide.

Thank you.

**Comment by kytrinyx** [comment] 2016-04-19 10:15
This information is great, thanks. It looks like the API endpoint isn't returning a timestamp anymore. I'll take a look.

**Comment by kytrinyx** [comment] 2016-05-02 12:19
Sorry it's taken so long to get back to you. I wonder if we have a bad release out in the wild.

I have tried to reproduce this behavior by installing the lastest (2.2.5) version in three different ways:

1. from source on my machine with `go install`
1. via homebrew with `brew update && brew uninstall exercism && brew install exercism`
1. by downloading the latest release on GitHub https://github.com/exercism/cli/releases/tag/v2.2.5

All three of these methods resulted in a successful status command.

How did you install this version of the CLI? Would you try reinstalling the latest release to see if that fixes it?

**Comment by kytrinyx** [comment] 2016-05-02 12:20
Oh, wait. No I forgot the "after a fresh fetch" step!

I've reproduced the issue.

**Comment by kytrinyx** [comment] 2016-05-02 12:25
Update: No, I am not sure that I have. I can reproduce this only if I fetch something on a language track where I've not submitted anything. In this case We should be saying "you haven't started the track yet", I think.

If you are getting this error message on a track that you've actually started, would you see if you can figure out the reproduction steps?

**Comment by kytrinyx** [comment] 2016-05-02 12:33
I've tweaked the behavior of the API to return "you haven't started this track yet" so that the client doesn't blow up, but we might want to discuss whether or not an unstarted track where you've fetched something should tell you about what you fetched.

**Comment by duckpuppy** [comment] 2016-05-04 20:12
Should this be fixed now?  I still see the "cannot parse" error on tracks with no submissions.  I'm using the cli as installed by homebrew on OSX, version 2.2.5.

**Comment by kotp** [comment] 2016-05-04 20:55
Looks like #316 may be either duplicated or related.

I can confirm that I have a track where it has been fetched but nothing submitted, I get the same message.

**Comment by kytrinyx** [comment] 2016-05-05 07:44
This is still a problem. I wrote the fix and forgot to merge it to master. I'll do this when I've had some sleep.

**Comment by duckpuppy** [comment] 2016-05-06 21:24
@kotp I can see related, but it's not really duplicated - I have submissions on the track already and have fetched the next exercise.

**Comment by kotp** [comment] 2016-05-06 22:16
I did say 'may be' as I am not positive.  @kytrinyx may have understanding that it is the exact mechanism in question causing both. Purely speculative, though.

**Comment by kytrinyx** [comment] 2016-05-07 01:45
Sorry--things got extremely out of control at the conference I was at. https://twitter.com/kytrinyx/status/728480126573285380

I'll get to this on the weekend.

**Comment by kytrinyx** [comment] 2016-05-08 18:30
OK, this is really dirty, and we can't fix it properly without changing the CLI, which will require a new release.

Here's the temporary solution:

```
$ exercism status lisp

Your status on the lisp track:

Most recently submitted exercise:
 - You have not yet submitted exercises to track lisp. (submitted on May 8, 2016)

Exercises fetched but not submitted:
 - sorry, tracking disabled for fetching
```

**Closed** 2016-05-08 18:31 UTC
