### ISSUE TITLE
Update broken urls

### ISSUE THREAD

**Issue by NChechulin** [exercism/cli#1016] opened 2021-12-02 09:25 UTC
Exercism CLI still provides "old" links.
As far as I understand, the whole project moved to https://exercism.org/, but some output still contains `https://exercism.io/`.

Example:
```sh
$ exercism configure 
> Error: There is no token configured. Find your token on https://exercism.io/my/settings, and call this command again with --token=<your-token>.
```

Exercism version: `3.0.13`

**Comment by kotp** [comment] 2021-12-02 18:59
Can you give the version as reported by `exercism -v`?

**Comment by NChechulin** [comment] 2021-12-02 21:10
Oh, it seems like `-v` stands for `--verbose` and `exercism --help` also doesn't provide a flag for version.
However, I am using the last version from AUR: `3.0.13-1`

**Comment by kotp** [comment] 2021-12-03 01:13
Oops.  I should have said `exercism v` rather than `exercism -v`.  Or `exercism version`.  Habit put that dash in there.

**Comment by miwojc** [comment] 2022-02-13 07:07
exercism version 3.0.13
Windows 10

`exercism submit .\twelve_days.py` returns a link to 404 page:

>     The exercise you are submitting doesn't have the necessary metadata.
>     Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.

**Comment by kotp** [comment] 2022-02-13 07:59
The referece to `io` is probably not a functional issue, rather a documentation issue.  Version 3.0.13 is fine, and should not have an issue.

The issue is specifically indicating that the `./.exercism/` directory is not there.

If you do `exercism download --track=python --exercise=twelve-days` is the current directory where it is downloaded it?

**Comment by miwojc** [comment] 2022-02-13 08:40
```exercism download --track=python --exercise=twelve-days```
solved the issue for me. Thank you.

**Comment by kotp** [comment] 2022-02-13 09:04
I would say that it solved your immediate issue, however the updated URL issue is still something that should be fixed.

Would you care to update the title of this issue to reflect the desired correction to the URL as stated in the error message?

**Comment by miwojc** [comment] 2022-02-13 11:52
@NChechulin opened this issue, so i can't edit title but i think title and description is correct?

**Comment by NChechulin** [comment] 2022-02-13 12:41
@kotp Hi! When I opened the issue, I tried to emphasize the breadth of the problem. I believe, it's not about one or several particular commands, but about the whole project in general.

That's why the title is kind of very general.

**Comment by kotp** [comment] 2022-02-13 15:09
@NChechulin Yes, it probably is not wrong, but now we can focus it on "Error message shows URL as `.io` instead of `.org`."

**Closed** 2024-11-03 15:17 UTC
