### ISSUE TITLE
manifest parse error(s): 1 swift package

### ISSUE THREAD

**Issue by shleykin** [exercism/cli#813] opened 2019-02-26 10:36 UTC
Hello !

I am trying to configure Xcode and running tests(swift) ,error occurs at this stage:

_execute swift package generate-xcodeproj_

Error:

l3mac:hello-world l3$ swift package generate-xcodeproj
/Users/l3/Exercism/swift/hello-world: error: manifest parse error(s):
1
I tried to find a solution, so far without success, maybe you will help, thanks in advance!

Xcode Version 10.1 (10B61)
mojave 10.14.3

swift tests
swift builds

same error

exercism version 3.0.11
Your system is ready to brew.

**Comment by shleykin** [comment] 2019-02-26 10:38
exercism version 3.0.11
Your system is ready to brew.

**Comment by NobbZ** [comment] 2019-02-26 11:09
As far as I can tell, this is not caused by the `exercism` CLI.

Could you please re-open a ticket at https://github.com/exercism/exercism and also mention the `@exercism/swift`-team?

**Comment by kytrinyx** [comment] 2019-02-26 23:47
This problem is unrelated to Exercism. I think your best bet is to find a swift-specific forum to get help with troubleshooting (or perhaps join the CodeNewbie community, who might have some swift enthusiasts who can help you out).

I'm going to close this, since we're unable to help here.

**Closed by kytrinyx** 2019-02-26 23:47 UTC
