### ISSUE TITLE
Homebrew bash/zsh completion

### ISSUE THREAD

**Issue by mulderje** [exercism/cli#394] opened 2017-05-30 00:48 UTC
I noticed that the bash/zsh completion files aren't included in the install tar files, and am unsure what the generation process looks like. If not included in the tar files, have you considered leveraging the [Homebrew resource calls](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#specifying-gems-python-modules-go-projects-etc-as-dependencies) the the cli website and installing that way?

Also happy to put this over in the Homebrew repo if more appropriate, but figured I would start here since the files didn't seem to be in the tars.

https://github.com/Homebrew/homebrew-core/blob/c53141dcda9d1a062eba89f77a5c02f09f6b5bd2/Formula/exercism.rb

Thanks,
jon

**Comment by tengwar** [comment] 2017-07-07 19:42
There's the same problem with Linux tarballs - they contain the executable and nothing else.

**Comment by kytrinyx** [comment] 2017-08-04 21:40
This is a great point. We should definitely consider adding these to the build script.

I need to figure out how to tell Homebrew where to put the auto-complete scripts, or if it has some good defaults.

**Comment by kytrinyx** [comment] 2018-06-10 23:54
I'm closing this as a duplicate of https://github.com/exercism/cli/issues/508

**Closed by kytrinyx** 2018-06-10 23:54 UTC
Labels: pinned, release-process
