### ISSUE TITLE
Exercism should not show "Not in Workspace" just because the filesystem is case insensative

### ISSUE THREAD

**Issue by yyyc514** [exercism/cli#930] opened 2020-04-27 03:44 UTC
**To reproduce:** 

On a Mac, or anywhere with case insensitive filesystem I'd assume)

If your folder is configured to be "Exercism" (with a caps):

```shell
# note the lowercase exercism
cd ~/exercism/language/exercise
exercism submit file.js
```

**Desired behavior:**

This should "just work", regardless of the case that was used when the user changed into the directory in the shell.  It's the same folder either way.

Perhaps there is some way to ask for a canonical path and use that?

**Comment by chocopowwwa** [comment] 2020-04-27 05:38
Hi, I'd like to try to debug your problem.

Can you provide your `$HOME/.config/exercism/user.json` (don't forget to sanitize your token)? I need the workspace key to debug your CLI.

**Comment by yyyc514** [comment] 2020-04-27 05:41
It doesn't need to be debugged.  The problem is:

```
"workspace": "/Users/jgoebel/Exercism"
```

But I was (thanks to tab completion) in `exercism`.  When I changed directory to the capitalized version it worked fine. **The CLI should be smarter about this.**

**Comment by yyyc514** [comment] 2020-04-27 05:42
Does Go have no way to get a canonical path?

**Comment by chocopowwwa** [comment] 2020-04-27 06:57
>  The CLI should be smarter about this.

I understand your frustration, but hey, at least you can submit your solution, right?

> Does Go have no way to get a canonical path?

There is, and I believe this CLI has done so, but the problem is, it doesn't handle the case-insensitive FS
https://github.com/exercism/cli/blob/master/workspace/workspace.go#L123

**Comment by iHiD** [comment] 2020-04-27 10:26
Thanks for reporting Josh.  Probably all software should be smarter about lots of things :)

I'm closing as a duplicate of https://github.com/exercism/cli/issues/637

It's on the radar and will get fixed at some indeterminate time in the future. Also see this comment thread: https://github.com/exercism/cli/issues/911#issuecomment-577752555

**Closed by iHiD** 2020-04-27 10:26 UTC

**Comment by yyyc514** [comment] 2020-04-27 14:33
Oh I did scan the list first but I missed that.

**Comment by iHiD** [comment] 2020-04-28 13:48
Btw, thanks @chocopowwwa for trying to help :)

**Comment by yyyc514** [comment] 2020-04-28 14:58
> Does Go have no way to get a canonical path?

I meant something like `realPath` or `canonicalPath` such that:

```js
canonicalPath("/users/JGOEBEL/exercism/JavaScript/") =>
"/Users/jgoebel/exercism/javascript"
```

Seems like a method that would be pretty useful.

@chocopowwwa I wasn't trying to be ungrateful, BTW. I just understood the problem fully at that point and was just posting it so someone could perhaps fix it. :-)

**Comment by NobbZ** [comment] 2020-04-29 18:57
No, go does not have such a thing built in.

Though if you can point me to a language that has something like that implemented in the stdlib or an external library that works cross platform, I'm happy to dig the source code and try to implement something functionally identical in go. Though the last snippet we found, had a lot of bugs and missing edge cases.

**Comment by yyyc514** [comment] 2020-04-29 19:26
Ruby seems to do the right thing by default if you just ask it for the current path:

```
~ % cd exercism # wrong path                                               
~/exercism % irb                                                           
irb(main):001:0> Dir.pwd()
=> "/Users/jgoebel/Exercism"
```

**Comment by NobbZ** [comment] 2020-04-29 19:49
Skimming the code (implemented in C), it seems as if canonicalisation only happens when `__APPLE__` is defined as a pre processor macro. I doubt this will work on windows.

Anyway, if we can use this, to at least get a better result on mac, then we are a big step further than were we are now.

**Comment by yyyc514** [comment] 2020-04-29 19:52
I thought we wanted to know how it was done? :-)  I wasn't suggesting we switch the client to Ruby. :-)

What happens when __APPLE__ is defined, does it do some additional magic?

**Comment by NobbZ** [comment] 2020-04-29 19:56
Yeah, what I wanted to say is, that we can take a look at it, but it wont solve all of our problems.

**Comment by yyyc514** [comment] 2020-04-29 20:24
Are you sure that's not a red herring?  I went down a few rabbit holes just now and a LOT of that looks to be UTF8 and encoding relating stuff... no the path normalization  (despite the naming)... I could be wrong... but I think BSD's `getcwd` is doing this all on its own:

```
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getcwd.3.html
```

**Comment by yyyc514** [comment] 2020-04-29 21:03
```go
package main

import (
    "fmt"
    "syscall"
)

func main() {
    pwd, _ := syscall.Getwd()
    fmt.Println(pwd)
}
```

This code works for me, always returning the accurate path. The problem with `os.Getwd()` (and friends I'd imagine) is that it first tries to "cheat" by just comparing the PWD with `statNolog(".")`. 
It even calls it a kludge, so I'm not sure of the WHY behind this. I'd presume for some reason that is a case insensitive compare so never actually does a real syscall.  

<https://golang.org/src/os/getwd.go?s=620:656#L31>

Perhaps the syscall is more expensive?

**Comment by yyyc514** [comment] 2020-04-29 21:05
Not sure this helps since I guess we take the name of the file as input... although I'm not sure if that's on purpose... I've never run submit outside of the CWD of the exercise personally.

**Comment by yyyc514** [comment] 2020-04-29 21:06
Actually on Windows and plan9 the syscall is the first thing it tries:

```
	if runtime.GOOS == "windows" || runtime.GOOS == "plan9" {
 		return syscall.Getwd()
	}
```
