### ISSUE TITLE
Problem Submitting Hello World

### ISSUE THREAD

**Issue by wuedson** [exercism/cli#950] opened 2020-08-06 04:48 UTC
Hi, I have just started using Exercism, and I am having problems submitting my code.

My workspace is the following:
C:\Users\1540 LITE\Exercism

I am trying to submit my answer using:
C:\Exercism>exercism submit C:\Users\1540~\Exercism\python\hello-world\hello_world.py

But I get the following error: 
The file you are trying to submit cannot be found.

        C:\Users\1540~\Exercism\python\hello-world\hello_world.py

These are the files in the folder with the hello_world.py:

![image](https://user-images.githubusercontent.com/14941975/89491994-29770480-d776-11ea-8866-8b0ec0c655e3.png)

Thank you in advance,
Edson

**Comment by kotp** [comment] 2020-08-06 06:10
It is very likely due to the space in the directory name causing some issues.  The file also does not appear to be in the workspace, which may also prevent it from being sent.

Instead, we would usually change to the directory that was reported when the exercise was downloaded, apparently in this case the `C:\Users\1540~\Exercism\python\hello-world\` directory.  And then using:

```
exercism submit hello_world.py
```

Which would end up being easier to type anyway.  But the workspace and the folder name being two different things is not a good indication.

**Comment by wuedson** [comment] 2020-08-06 13:26
Thank you very much! I have just submitted!

I wasn`t doing what you told me because I hadn`t added the exercism folder to the path, so I had errors when I used exercism submit.

Edson



________________________________

**Comment by kotp** [comment] 2020-08-07 21:44
Looks like the problem is solved, so closing.  Feel free to reopen if this is not the case.

**Comment by NobbZ** [comment] 2020-08-08 06:31
I'll close for @kotp.

Please reopen if necessary @wuedson.

**Closed by NobbZ** 2020-08-08 06:31 UTC
