### ISSUE TITLE
"Please provide your Exercism.io API key"

### ISSUE THREAD

**Issue by ZenoArrow** [exercism/cli#159] opened 2015-02-04 11:33 UTC
Hi,

Using the Windows CLI. Try using http://x.exercism.io/v2/exercises/fsharp?[APIKEYHERE].

Getting a timeout in the CLI. If I try the URL in a browser, I get {"error":"Please provide your Exercism.io API key"} . 

Not sure why.

FYI, I also get a CLI timeout using http://x.exercism.io/tracks, but I'm able to access this page via a browser.

Any ideas what I can try to fix this? Let me know if I can provide more useful debugging information.

**Comment by kytrinyx** [comment] 2015-02-04 14:35
What does `exercism debug` output? Does the api key start with dbb2?

**Comment by ZenoArrow** [comment] 2015-02-04 15:02
Hi kytrinyx, thanks for getting back to me so quickly.

Here's the output of exercism debug (API key removed):

**** Debug Information ****
Exercism CLI Version: 1.9.2
OS/Architecture: windows/amd64
Home Dir: C:\Users\t.clarke
Config file: C:\Users\t.clarke\.exercism.json
API Key: dbb2...
API: http://exercism.io
Exercises Directory: C:\Users\t.clarke\exercism

API key does indeed start with dbb2, and is 32 characters long.

I'm at work, perhaps there's an issue with the work proxy, but I somewhat doubt it (as otherwise the whole x.exercism.io domain would be blocked). Any ideas of what I could try?

**Comment by ZenoArrow** [comment] 2015-02-04 20:51
Just to continue testing, I installed the same exercism CLI tool (v.1.9.2, Win 64bit), and used the same CLI environment (PowerShell v4.0) on a different PC on a different network. Worked first time.

This does add weight to the idea that the issue was with my work network. I'd like to help further to see if we can improve the debug output to include network status, is this something I can help you test?

**Comment by lcowell** [comment] 2015-02-04 22:11
Perhaps we could add a check to the debug output, that exercism can talk to the api and xapi hosts ?

**Comment by kytrinyx** [comment] 2015-02-05 02:11
@lcowell that's a great idea!

**Comment by ZenoArrow** [comment] 2015-02-05 09:21
@lcowell I agree with @kytrinyx , great idea.

Is there a good chance this could be added to the next version of the CLI?

**Comment by kytrinyx** [comment] 2015-02-05 14:43
I can't promise a timeline, but it wouldn't be too difficult to add.

**Comment by ZenoArrow** [comment] 2015-02-05 17:40
Okay thanks. Just so you know, I'm happy to test it when it is available.

**Comment by lcowell** [comment] 2015-02-05 23:23
OK, so I've got something really simple working. If everything looks good, it says:

```
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
```

Otherwise it puts the error message between the brackets.
```
API: http://localhost:8000 [Get http://localhost:8000: dial tcp 127.0.0.1:8000: connection refused]
XAPI: http://localhost:8000 [Get http://localhost:8000: dial tcp 127.0.0.1:8000: connection refused
```

**Comment by kytrinyx** [comment] 2015-02-06 03:02
This looks great.

**Comment by ZenoArrow** [comment] 2015-02-06 12:48
Looking forward to trying it out. :-)

**Comment by lcowell** [comment] 2015-02-06 18:32
@ZenoArrow I've pushed up that additional debugging output. Are you in a position to build from source so you can test it out ?

**Comment by kytrinyx** [comment] 2015-02-07 04:05
I'll cross-compile a release candidate

**Comment by kytrinyx** [comment] 2015-02-07 04:12
Update: I'm going to have to debug some build stuff on my machine, but can't do it today. I'll post an update this weekend.

**Comment by ZenoArrow** [comment] 2015-02-07 07:25
@lcowell Thanks so much! Haven't got a build environment set up, so will wait for @kytrinyx 's update.

**Comment by kytrinyx** [comment] 2015-02-07 20:04
Ok, @ZenoArrow here you go: https://github.com/exercism/cli/releases/tag/v2.0.0.beta.1

**Comment by ZenoArrow** [comment] 2015-02-10 17:15
Thanks @kytrinyx . I have tested it on the machine that had the issue previously, looks like the API and XAPI checks are working as expected: 

**** Debug Information ****
Exercism CLI Version: 2.0.0.beta.1
OS/Architecture: windows/amd64
Home Dir: C:\Users\t.clarke
Config file: C:\Users\t.clarke\.exercism.json
API Key: dbb2...
API: http://exercism.io [Get http://exercism.io: net/http: request canceled while waiting for connection]
XAPI: http://x.exercism.io [Get http://x.exercism.io: net/http: request canceled while waiting for connection]
Exercises Directory: C:\Users\t.clarke\exercism

Thanks to @lcowell also for making these changes.

Guess we can close this issue now, but before you do can I check... what port is being used for the API and XAPI connection? Is there a chance of trying the API over port 443 or port 80, i.e. could I run any tools to check I can access the APIs over these ports?

**Comment by kytrinyx** [comment] 2015-02-11 02:35
Both of the connections are on port 80. Could this be a firewall issue? Someone added some troubleshooting steps for that: http://help.exercism.io/troubleshooting.html

**Comment by kytrinyx** [comment] 2015-02-11 02:36
I'll go ahead and close it, since it seems like the problem is on the machine, not in the client, but keep posting and we'll keep doing what we can to help figure out what's going on.

**Closed by kytrinyx** 2015-02-11 02:36 UTC
Labels: support
